"""updating dog_owners table

Revision ID: 0164580b3a31
Revises: ae8de95a07a1
Create Date: 2024-01-11 15:21:49.333803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0164580b3a31'
down_revision: Union[str, None] = 'ae8de95a07a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog_owners', sa.Column('email', sa.String(), nullable=True))
    op.add_column('dog_owners', sa.Column('about_me', sa.String(), nullable=True))
    op.add_column('dog_owners', sa.Column('username', sa.String(), nullable=True))
    op.add_column('dog_owners', sa.Column('password_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_dog_owners_username'), 'dog_owners', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dog_owners_username'), table_name='dog_owners')
    op.drop_column('dog_owners', 'password_hash')
    op.drop_column('dog_owners', 'username')
    op.drop_column('dog_owners', 'about_me')
    op.drop_column('dog_owners', 'email')
    # ### end Alembic commands ###
