"""updating dog_owners table to only include id, username, and about_me

Revision ID: a1d1e3da1264
Revises: 49e62994b49f
Create Date: 2024-01-11 15:39:51.857512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d1e3da1264'
down_revision: Union[str, None] = '49e62994b49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog_owners', 'password_hash')
    op.drop_column('dog_owners', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog_owners', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dog_owners', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
