"""create dog_owners table

Revision ID: ae8de95a07a1
Revises: 8bb706013584
Create Date: 2024-01-11 15:16:09.369343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8de95a07a1'
down_revision: Union[str, None] = '8bb706013584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('about_me', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dog_owners_id'), 'dog_owners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dog_owners_id'), table_name='dog_owners')
    op.drop_table('dog_owners')
    # ### end Alembic commands ###
