"""Added auth columns to Dog Owner

Revision ID: ccd1a8d2eae3
Revises: ae8de95a07a1
Create Date: 2024-01-12 11:08:17.596269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd1a8d2eae3'
down_revision: Union[str, None] = 'ae8de95a07a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog_owners', sa.Column('email', sa.String(), nullable=True))
    op.add_column('dog_owners', sa.Column('password_hash', sa.String(), nullable=True))
    op.alter_column('dog_owners', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dog_owners', 'about_me',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_dog_owners_email'), 'dog_owners', ['email'], unique=True)
    op.create_index(op.f('ix_dog_owners_username'), 'dog_owners', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dog_owners_username'), table_name='dog_owners')
    op.drop_index(op.f('ix_dog_owners_email'), table_name='dog_owners')
    op.alter_column('dog_owners', 'about_me',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dog_owners', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('dog_owners', 'password_hash')
    op.drop_column('dog_owners', 'email')
    # ### end Alembic commands ###
